kci-dev/kci-dev.py
kci-dev/libs/common.py
kci-dev/subcommands/commit.py
kci-dev/subcommands/patch.py

1)Moving load_toml to main file, as it is common for all files. 2)Adding context to forward instance and settings to subcommands 3)Modifying at least "commit" subcommand to support latest Pipeline API 4)Add automatic repo info retrieval for "commit" with option to override by cli arguments.

feat(all): Add global parameters

---

docs/index.md
kci-dev/kci-dev.py
kci-dev/subcommands/testretry.py
tests/test_kcidev.py

Add command to retry some tests, in case test are flaky and we need to make sure it is not some glitch or hardware issue, by re-running the test.

feat(testretry): Add testretry command

---

docs/checkout.md
kci-dev/subcommands/checkout.py

Watch interactively results of custom checkout, each step, until job is completed.
Example:
./kci-dev.py checkout --giturl https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git --branch master --tipoftree --jobfilter baseline-nfs-arm64-qualcomm --jobfilter kbuild-gcc-12-arm64-chromeos-qualcomm --watch
Output example:
./kci-dev.py checkout --giturl https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git --branch master --tipoftree --jobfilter baseline-nfs-arm64-qualcomm --jobfilter kbuild-gcc-12-arm64-chromeos-qualcomm --watch
api connect: https://staging.kernelci.org:9100/
Retrieving latest commit on tree: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git branch: master
Commit to checkout: d3d1556696c1a993eec54ac585fe5bf677e07474
OK
Watching for …

feat(checkout): Add --watch option

---

docs/checkout.md
kci-dev/subcommands/checkout.py

Add test option, last step before implementing bisect subcommand.

Add test option

---

kci-dev/subcommands/checkout.py

As we upgraded pydantic, there is some schema changes and field _id is translated to id.
Update code, and avoid exception if we hit old endpoint.

fix(checkout.py): Due pydantic update change field name

---

.github/workflows/pypi-publish.yml
.github/workflows/pypi-test.yml

This pull request will publish kci-dev to PyPI automatically when a new release is published
Will also publish to test.pypi when the following tags are matched
```
- "v*.*.*.dev*"
- "v*.*.*.post*"
- "v*.*.*.rc*"
- "v*.*.*.a*"
- "v*.*.*.b*"
```

github/workflows/pypi-test: Publish new release on pypi

---

kcidev/subcommands/checkout.py

In some conditions, when job is itself test result (some regressions cause that), we must fail on it as failed test, if it is set in --test argument, to bisect correctly.

fix(checkout): Do not consider failed job as infra failure

---

docs/index.md
kcidev/libs/common.py
kcidev/main.py

Implement support for a global configuration file to enable kci-dev functionality across any source directory location, but keep support of local configuration file. This enhancement will allow for more flexible project setup and improved workflow portability.

Add global config

---

kcidev/libs/common.py
kcidev/main.py

While doing global settings change due bad internet connection i reversed to old version by mistake. This will fix https://github.com/kernelci/kci-dev/pull/42 and make it work as intended.

fix(common.py/main.py): Fix global settings changes

---

kcidev/libs/common.py

Users will be clueless for a moment if we give them a dump, instead of a clear message.

config: show a nice error message if not config is available

---

kcidev/subcommands/checkout.py

In some cases (typo/mistake) we cannot retrieve commit id, we must generate proper error that will hint what might be the reason.

fix(checkout): Properly handle if we cannot retrieve tip of tree

---

README.md
docs/_index.md
docs/maestro-results.md
docs/results.md
kcidev/libs/common.py
kcidev/main.py
kcidev/subcommands/maestro_results.py
kcidev/subcommands/results.py
tests/test_kcidev.py

Add PoC for `kci-dev results` from the [Dashboard API](https://github.com/kernelci/dashboard/blob/main/backend/kernelCI_app/urls.py).
See the `docs/results.md` for details about this command. For the time being, it will be experimental as we refine how together with kernel developers how they are going to be using `kci-dev`.
There is a know slowdown in the API due to https://github.com/kernelci/dashboard/issues/661.
Related to #57

Experimental command to fetch results from the Dashboard API

---

kcidev/libs/common.py
kcidev/subcommands/results.py

Make the output easir to understand and parse. Before we were just printing json.
``` 
kcidev > poetry run kci-dev results  --commit 4b281055ccfba614e9358cac95fc81a1e79a5d7e --giturl 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git' --branch linux-5.15.y
pass/fail/inconclusive
builds:	29/1/0
boots:	411/67/22
tests:	2584/347/191
```

results: improve output of the summary cmd

---

docs/results.md
kcidev/libs/common.py
kcidev/subcommands/results.py

Improve usability by:
* showing all builds, not only failing builds
* filtering for pass or fail
* color highlight to output
* add commit hash to log file name to avoid clash with files from a different revision.

Refactor 'results --action=builds' 

---

.github/workflows/pypi-publish.yml

"on: release:" workflow catches also dev release, but dev release are published only on testing PyPI, at the moment

pypi-publish: publish only with a production tag

---

kcidev/main.py
kcidev/subcommands/bisect.py

When kernel breaks we need to be able to use automated way bisection, using bisect command. This is initial version, that just works, but needs a bit more work to work reliably. I prefer to commit early, so we don't accumulate too much uncommited code.

feat(bisect): Add new bisection feature

---

pyproject.toml

resolves #79
Added sdist and wheel as format on pyproject.toml as a temporary fix for poetry format issue
bug: https://github.com/python-poetry/poetry/issues/9961

poetry/ci: Fix poetry 2.0.0 compatibility

---

docs/checkout.md
kcidev/subcommands/bisect.py
kcidev/subcommands/checkout.py

1)If linux tree source code doesn't exist (workdir), bisection will fail due wrong sequence of commands.
2)Change parameter names from platformfilter and jobfilter to job-filter and platform-filter

fix(bisect.py): Fix initial tree creation and params rename

---

kcidev/subcommands/bisect.py
kcidev/subcommands/checkout.py
kcidev/subcommands/maestro_results.py
kcidev/subcommands/testretry.py

Thi commit changes all secho error messages with fg="red" as parameter to kci_err().

use kci_err() for error messages across codebase

---

docs/checkout.md
kcidev/libs/common.py
kcidev/libs/maestro_common.py
kcidev/subcommands/bisect.py
kcidev/subcommands/checkout.py
kcidev/subcommands/maestro_results.py
kcidev/subcommands/patch.py
kcidev/subcommands/testretry.py

We have proved that these cmds are useful. Now we need to do a serious cleanup as we move to increase our user base and expand what the kci-dev tooling can do.

General improvements to maestro commands

---

docs/results.md
kcidev/subcommands/results.py
kcidev/subcommands/sub.py

As discussed in #65, fix 'results' to use subcommands:
$ kci-dev trees
$ kci-dev summary
$ kci-dev builds
This is much cleaner interface and a request from users.

Turn results --action into subcommands

---

kcidev/libs/common.py
kcidev/subcommands/bisect.py
kcidev/subcommands/commit.py
kcidev/subcommands/maestro_results.py
kcidev/subcommands/patch.py
pyproject.toml

pyproject: Update toml dependency to tomllib

---

kcidev/subcommands/results.py

configparser usually complain about multiple entries for the same option.
Using strict=False allow duplicate entries, like in the case of multiple "fetch=" entries on the same section.

results: Parse git configuration with configparser with strict=False

---

docs/results.md
kcidev/subcommands/results.py

This solve error when parsing detached head commit

results: Use git rev-parse for getting commit hash

---

kcidev/subcommands/config.py

Both of the pypi and poetry path was pointing to the same poetry path. This was giving a not found error in the case of kci-dev not using poetry. Also normalized both path.

config: Fix example configuration path

---

docs/checkout.md
kcidev/subcommands/bisect.py
kcidev/subcommands/checkout.py

Sometimes when we issue invalid command during bisect, we need to be less obscure why did it happen and how to reproduce. Also use a bit more correct job-filter/platform-filter commands, even underscore works too.
Example:
```
ci-dev bisect --workdir kcidev-src/ --giturl https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git --branch linux-5.15.y --job-filter kbuild-gcc-12-x86 --job-filter baseline-x86-intel --test baseline-x86-intel --platform-filter acer-chromebox-cxi4-puff --good 3a5928702e7120f83f703fd566082bfb59f1a57e --bad 584a40a22cb9bf5a03135869f11c3106b6200453
Loaded state file
giturl: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git
branch: linux-5.15.y
good: 3a5928702e7120f83f703fd566082bfb59f1a57e
bad: …
```

fix(docs,bisect,checkout): Improve debug output on failures

---

kcidev/subcommands/results.py

We were using the wrong var in the error string.

results: fix crash when log file is not found

---

docs/_index.md
docs/checkout.md
docs/watch.md
kcidev/libs/maestro_common.py
kcidev/main.py
kcidev/subcommands/checkout.py
kcidev/subcommands/maestro_results.py
kcidev/subcommands/watch.py

Sometimes we are anxious to follow the result of a test, or just hit CTRL-C accidentally on a checkout command, so let's have a way to just watch for the results of a node.

Add watch command

---

kcidev/subcommands/bisect.py

We need to make it more robust and improve the output of the command to give users as easy experience.

Initial improvements to the bisection tooling

---

kcidev/libs/common.py
kcidev/libs/maestro_common.py
kcidev/main.py
kcidev/subcommands/checkout.py
kcidev/subcommands/watch.py

Show only relevant information. Next step we will add an option to download the logs.

Improve watch command output

---

docs/results.md
kcidev/subcommands/results.py

Now you can pass a list of tests to the yaml filter to select only specific tests you want to see.

results: add test filter to the `tests` command.

---

kcidev/subcommands/maestro_results.py

We need either --nodes or --nodes to be supplied.

maestro_results: throw error if required options are missing

---

kcidev/subcommands/checkout.py

Print treeid and checkout nodeid by default to help scripts calling kci-dev parse the checkout response. This allows retrieving the build nodeid for a given checkout nodeid.

checkout: print treeid and checkout nodeid by default

---

.github/workflows/poetry.yml
pyproject.toml
scripts/check.sh
tox.ini

Ref: https://peps.python.org/pep-0701/

pyproject: Add testing for different python versions with tox

---

kcidev/subcommands/results.py

Sometimes KCIDB/dashboard won't gives the data back and throw a 500 instead. Let's have an automatic retry there to reduce the chance of seeing such an error.

results: add retry logic if we meet server error

---

docs/results.md
kcidev/subcommands/results.py

Displays the number of results after applying all filters

results: add --count to boots, builds and tests

---

docs/results.md
kcidev/subcommands/results.py

Formats results in a json. It also affects flags like  --count.

results: add --json flag

---

docs/results.md
kcidev/libs/dashboard.py
kcidev/libs/files.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/results/parser.py

The command accepts --id <test_id>, along with --json and --download-logs.
We also move the download logs function to libs/files.py and create a function that verifies that creates portable filenames.
fixes #136

Add kci-dev results test subcommand

---

kcidev/libs/dashboard.py
kcidev/libs/git_repo.py
kcidev/subcommands/results/__init__.py

Only errors written to stdin use the --json flag.
fixes #141

Format error as json when using --json

---

docs/results.md
kcidev/libs/dashboard.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/results/parser.py

displays all the information of the build with the given id
fixes #137

kci-dev results build subcommand

---

docs/results.md
kcidev/libs/dashboard.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/results/hardware.py
kcidev/subcommands/results/options.py
kcidev/subcommands/results/parser.py

Adds the hardware list subcommand

feat: hardware subcommand

---

docs/results.md
kcidev/libs/dashboard.py
kcidev/subcommands/results/hardware.py

Subcommand hardware summary --name --origin

---

kcidev/libs/files.py
kcidev/libs/git_repo.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/results/hardware.py
kcidev/subcommands/results/parser.py

Some modules were considering relative imports to other parts of the client. This works on a local enviroments but fails when installing the client using pip or packaging the code

Fix: Turn relative imports to absolute imports

---

kcidev/subcommands/results/parser.py

Commit d45d0db ("Format error as json when using --json") added a new positional argument called **use_json** to the `dashboard_api_fetch()` method while fixing something else.
As part of the change, most of the callers of the `dashboard_api_fetch()`, such as the `dashboard_fetch_tree_list()` helper, were updated to correctly pass the new argument around.
However, the `cmd_list_trees()` was not updated to pass the new argument correctly to the aforementioned helper function, which it uses internally.
As such, when using kci-dev with the "results trees" subcommand, this results in a `TypeError` as follows:
```
TypeError: dashboard_fetch_tree_list() missing 1 required positional argument: 'use_json'
```
Thus, add the missing argument when invoking `dashboard_fetch_tree_list()` to fix the …

results: Fix dashboard_fetch_tree_list() invocation

---

CONTRIBUTING.md

The contributions guidelines are updated to include a suggested format based on the Conventional Commits specification.

docs(contributions): add suggested commit format

---

docs/results.md
kcidev/libs/dashboard.py
kcidev/subcommands/results/hardware.py
kcidev/subcommands/results/parser.py

Includes boots, builds and tests subcommands.
Below an example for each of them:
- Boots:
`kci-dev results hardware boots --name mediatek,mt8195 --origin maestro --status pass`
- Builds:
`kci-dev results hardware builds --compatibles mediatek,mt8195 --origin maestro `
- Tests:
`kci-dev results hardware tests --name amlogic,meson-gxl --origin maestro --status fail`

Hardware subcommands

---

docs/results.md
kcidev/subcommands/results/__init__.py

Add a `boot` subcommand to `results`.
Now we can both obtain all boots per tree and a single boot by id, just like with tests and builds.
The subcommand supports the same arguments as `results test`and `results build`. 
An example of usage would be:
```
kci-dev results boot --id 'maestro:67ffde3a69241b2ece0ccaa6' 
```

feat(results): Add boot subcommand

---

docs/results.md
kcidev/subcommands/results/parser.py

The `--filter` option allows passing a file that will work as a filter for picking results for a set of devices and tests. The filters are strict in the sense that the test path must match the filter exactly to be included in the results.
This PR allows referencing both hardware and tests using wildcards.
All of the follow would now be considered a valid reference to a test or set of tests: `kunit`, `kunit.*`, `kselftest.iommu.*`.
The new format would support a file like this:
```
hardware:
- radxa,rock2-square
- fsl,imx6q
- dell-latitude-3445-7520c-skyrim
test:
- kselftest.iommu.*
- kselftest.dt
- kunit.*
```
closes #163

Allow wildcards in filter file

---

kcidev/libs/git_repo.py

This PR improves the usability of the kci-dev results command by automatically detecting missing git parameters (URL, branch, commit) from the local git repository.
Previously, when using --giturl without specifying --branch, the command would fall back to using the default repository settings, often resulting in incorrect tree URLs being displayed and API errors. This made it cumbersome to check results for specific commits while working on a development branch.
The changes refactor set_giturl_branch_commit() to intelligently fill in any missing parameters from the local git repository:
- If --giturl is provided but --branch is missing, it uses the current branch from the local repo
- If --commit is missing (and --latest isn't specified), it uses the current HEAD commit
- If --giturl is …

Fix results command to auto-detect git parameters from local repository

---

kcidev/subcommands/bisect.py
kcidev/subcommands/checkout.py
kcidev/subcommands/commit.py
kcidev/subcommands/config.py
kcidev/subcommands/maestro_results.py
kcidev/subcommands/patch.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/testretry.py
kcidev/subcommands/watch.py

This PR adds detailed help text with usage examples to all kci-dev commands.
What changed:
- Added comprehensive help text explaining each command's purpose
- Included practical usage examples for all commands
- Commands now show help instead of errors when run without parameters (where applicable)
Commands updated: bisect, checkout, commit, config, patch, results, testretry, watch

Add comprehensive help documentation to all kci-dev commands

---

kcidev/libs/common.py
kcidev/libs/dashboard.py
kcidev/libs/files.py
kcidev/libs/filters.py
kcidev/libs/git_repo.py
kcidev/libs/job_filters.py
kcidev/libs/maestro_common.py
kcidev/subcommands/bisect.py
kcidev/subcommands/checkout.py
kcidev/subcommands/commit.py
kcidev/subcommands/config.py
kcidev/subcommands/maestro_results.py
kcidev/subcommands/results/parser.py
kcidev/subcommands/testretry.py
kcidev/subcommands/watch.py

This PR enhances debugging capabilities in kci-dev by adding logging throughout the codebase. When the --debug flag is enabled, users will now see detailed information about API requests and responses, git operations, file I/O, filter matching, and command execution.

Improve logging throughout the codebase

---

kcidev/libs/git_repo.py

Resolves #129 .
Built on top of PR #180 .

Resolve git tags

---

kcidev/libs/dashboard.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/results/parser.py

For the command `kci-dev results trees`, add `--days` option to provide a period of time in days to
get results for.
Closes https://github.com/kernelci/kci-dev/issues/176

Enable `--days` switch for getting tree list

---

kcidev/libs/common.py
kcidev/libs/git_repo.py
kcidev/libs/maestro_common.py
kcidev/main.py
kcidev/subcommands/maestro/results.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/results/parser.py
kcidev/subcommands/validate/__init__.py
kcidev/subcommands/validate/builds.py
kcidev/subcommands/validate/helper.py
pyproject.toml

Closes https://github.com/kernelci/kci-dev/issues/171
Get builds from dashboard and validate it with maestro result.
PR created on top of https://github.com/kernelci/kci-dev/pull/177 and https://github.com/kernelci/kci-dev/pull/179
Depends on https://github.com/kernelci/kernelci-api/pull/615

Implement command to validate builds

---

kcidev/libs/dashboard.py

By default dashboard API returns all boot results for a checkout from all the origins.
Add an option to filter boot results based on origin.

kcidev/libs/dashboard: add test filter option

---

kcidev/subcommands/results/parser.py

The kci_msg_nonl() function doesn't accept any parameters, but was being called with nl=False in print_summary(), causing a TypeError:
TypeError: kci_msg_nonl() got an unexpected keyword argument 'nl'
This fix removes the invalid parameter and uses the nl parameter correctly on the color message functions (kci_msg_green, kci_msg_red) instead.
Fixes: 19ae4b536e89 ("Add print summary function")

fix(results): remove invalid nl parameter from kci_msg_nonl calls

---

kcidev/libs/git_repo.py
kcidev/subcommands/validate/__init__.py
kcidev/subcommands/validate/boots.py
kcidev/subcommands/validate/builds.py
kcidev/subcommands/validate/builds_history.py
kcidev/subcommands/validate/helper.py

Implement `validate builds-history` command.
A builds history command to validate if number of builds is consistent for multiple checkouts of the same git  tree/branch.

Validate builds history

---

kcidev/subcommands/validate/helper.py

Add architecture filter for `validate builds` and `validate boots` commands.

Add `arch` filter for `validate` commands

---

kcidev/subcommands/maestro/validate/helper.py

Remove filter to exclude timed-out builds while getting builds from maestro.
This is due to maestro started sending timed-out builds to KCIDB as per the latest changes.
Reference: https://github.com/kernelci/kernelci-pipeline/pull/1227

Update filters for getting builds to validate

---

tests/test_kcidev.py

This PR adds comprehensive test coverage for all kci-dev results commands including summary, trees, boots, boot, tests, test, builds, and build commands. It covers command help validation, import testing, parameter validation, error handling, and end-to-end  functionality with real KernelCI data. 
Tests follow a consistent pattern for each command with help validation to ensure CLI  documentation is complete, import verification to confirm internal functions are accessible, parameter testing to validate required  inputs and error handling, and real data testing for end-to-end functionality with live KernelCI data.

Add tests for more results commands.

---

kcidev/libs/dashboard.py
kcidev/subcommands/results/__init__.py
kcidev/subcommands/results/issues.py
kcidev/subcommands/results/parser.py

A set of command to get the below information:
- Get issues
- Get issue information matching an ID
- Get builds associated with an issue
- Get tests associated with an issue

Implement a set of `results issues` command

---

kcidev/libs/common.py
kcidev/subcommands/maestro/validate/boots.py
kcidev/subcommands/maestro/validate/builds.py
kcidev/subcommands/maestro/validate/helper.py

Add new simple list output format as default for maestro validate builds command. The new format provides a cleaner, more readable view that:
- Shows tree/branch with ✅/❌ status indicators
- Lists commit hashes and missing build IDs with clickable links
- Groups results by tree/branch in history mode
- Focuses on highlighting discrepancies
Changes:
- Add print_simple_list() function with history and non-history modes
- Rename print_stats() to print_table_stats() for clarity
- Add --table-output option to use original table format
- Add kci_msg_bold_nonl() helper function for formatted output
- Update imports in boots.py to use renamed function
The simple list format is now the default, with --table-output available for users who prefer the detailed table view.

validate builds: improve output format with simple list view

---

kcidev/libs/common.py
kcidev/subcommands/maestro/validate/builds.py
kcidev/subcommands/maestro/validate/helper.py

1. Fix `print_simple_list` function:
- Add list of commits tested for builds history output
- Add number of missing builds to the ouput
2. Add `item_type` to `print_simple_list` to make it generic for builds and boots
3. Include commits in the output for which 0 builds are detected from the dashboard

`maestro validate builds` command fixes

---

kcidev/subcommands/maestro/validate/boots.py
kcidev/subcommands/maestro/validate/helper.py

Created on top of https://github.com/kernelci/kci-dev/pull/205
- Enable list view validation report for boots
- Handle case where no boots are found for a checkout

Boots validation: enable list view

---

kcidev/subcommands/results/parser.py

This can be used to extract lab information for the device where the test ran.

results: Add runtime field to boot and test JSON output

---

kcidev/libs/dashboard.py

Use `/tree` endpoint for fetching tree list as `/tree-fast` is not returning more than one entry for the same `git_url`, while /tree allows that.

kcidev/libs/dashboard: use `tree` endpoint instead of `tree-fast`

---

kcidev/subcommands/maestro/validate/helper.py

Maesto has enabled build/job retry support.
It retries `incomplete` builds and `fail/incomplete` boots for upto 3 times and send the final retry to dashboard.
Hence, adjust `maestro validate` tool to exclude incomplete/fail builds and boots as they won't be present on the dashboard.

Consider build/job retry while validating data
